[[reference-module-guidelines]]
= Reference Module Guidelines

A reference module lists things, such as a list of commands, or has a very regimented structure, such as the consistent structure of man pages. A reference module explains the details that a customer needs to know to do a procedure. A reference module is well-organized if users can scan it quickly to find the details they want.

//[bhardest] - We can include a diagram here if needed, similar to the concept one.

* A reference module that is a list of things may be made easier to scan if its content is organized alphabetically or formatted as a table. Think of an alphabetical list of commands that can be used with an application, or of an alphabetical list of system components with brief definitions formatted as a 2-column table.
// [bhardest] - This is a good use of a reference module; however, I've seen many different formats for this type of content in Red Hat product docs. It would help to provide some examples to help writers better visualize the techniques they can use to document these types of things in a clear, well-organized fashion.

* If you have a large volume of the same type of information to document, figure out a consistent structure into which the information details can fit, and then doument each logical unit of information as one reference module. For example, think of man pages, which document very different information details, but which still use consistent titles and formats to present those details in a consistent information structure.

== Related information

Download the reference module link:https://gitlab.cee.redhat.com/ccs-internal-documentation/Modular_Documentation_Project/raw/master/files/template_reference.adoc[template] for new projects.
