[id='anchor-and-file-names']
= Anchor Names and File Names

To optimize modular documentation, follow these guidelines for naming module anchors and files:

Anchor names:: Provide an anchor in the format `+++[id='anchor-name-{context}']+++` for every module so that it can be identified by Asciidoctor when reused or cross-referenced. `+++{context}+++` is a variable whose value you define in the assembly. Give the anchor the same or similar name as the module heading. Separate the words in the anchor with hyphens:
+
--
[source]
----
[id='anchor-name-{context}']
= Module Heading

The first sentence of the topic.
----

.Example 1. Concept Module
[source]
----
[id='guided-decision-tables-{context}']
= Guided Decision Tables

The guided decision tables feature works similarly to ...
----

.Example 2. Procedure Module
[source]
----
[id='creating-guided-decision-tables-{context}']
= Creating Guided Decision Tables

You can use guided decision tables to ...
----

[NOTE]
.Note on Other Anchor Formats (Not Recommended)
====
The format defined here is recommended because it is the most stable and versatile of anchor formats, and supports variables that enable topics to be reused and cross-referenced properly. For details, see xref:reusing-modules[]. Other anchor formats include `+++[[anchor-name]]+++` and `+++[#anchor-name]+++`, but these formats either do not support variables for content reuse or do not support certain character types, such as periods. These limitations cause errors at build time.
====

For more information about Asciidoc anchors, see the link:http://asciidoctor.org/docs/user-manual/#anchordef[Asciidoctor User Manual].
--

File names:: Give the module file the same name as the anchor used in it (which is the same as or similar to the module heading). Assembly and module file names should accurately and closely reflect the title of the assembly or module.
+
[NOTE]
====
Ensure that all members of your team use the same file naming conventions.
====
+
.Examples
* `guided-decision-tables.adoc`  (Concept module)
* `creating-guided-decision-tables.adoc`  (Procedure module for creating)
* `editing-guided-decision-tables.adoc`  (Procedure module for editing)
* `guided-decision-table-examples.adoc`  (Reference module with examples)
* `guided-decision-table-columns.adoc`  (Reference module with column types)
* `designing-guided-decision-tables.adoc`  (Assembly of guided decision table modules)

.Additional Resources

* The link:http://asciidoctor.org/docs/user-manual/#anchordef[Asciidoctor User Manual]
