[id="module_anchor-and-file-names-concept"]
= File names and anchors

To optimize modular documentation, follow these guidelines for naming files and creating anchors:

.File names
Create assembly and module file names that accurately and closely reflect the title of the assembly or module. Create file names with the format `prefix-filename.adoc` or `prefix_filename.adoc` where `prefix` is one of the following module prefixes:

* `con`: Concept module prefix
* `proc`: Procedure module prefix
* `ref`: Reference module prefix
* `assembly`: Assembly module prefix

.Examples
* `con-guided-decision-tables.adoc`  (Concept module)
* `con_guided-decision-tables.adoc`  (Concept module)
* `proc-creating-guided-decision-tables.adoc`  (Procedure module for creating)
* `proc_creating-guided-decision-tables.adoc`  (Procedure module for creating)
* `ref-guided-decision-table-examples.adoc`  (Reference module with examples)
* `ref_guided-decision-table-examples.adoc`  (Reference module with examples)
* `assembly-designing-guided-decision-tables.adoc`  (Assembly of guided decision table modules)
* `assembly_designing-guided-decision-tables.adoc`  (Assembly of guided decision table modules)


[NOTE]
====
Do not include special characters in file names. Ensure that all members of your team use the same file naming conventions.
====

These file naming guidelines are optional but highly recommended. However, if your team does not include the module prefixes in file names followed by either a hyphen (-) or an underscore (_), include one of the following variables in each file before the anchor ID:

[source]
----
:_content-type: ASSEMBLY
:_content-type: PROCEDURE
:_content-type: CONCEPT
:_content-type: REFERENCE
:_content-type: SNIPPET
----

.Anchors
At the top of every module, provide an anchor in the format `+++[id="filename_{context}"]+++` where `filename` is the exact name of the file, without the file extension (`.adoc`). Module anchors are necessary so that Asciidoctor can identify the module when the module is reused or cross-referenced. The  `context` variable is defined in each assembly module, such as `:context: my-context-value`. When you build an assembly, the value of the `context` variable replaces `context` in each module anchor ID and is displayed in the generated URL.

[source]
----
[id="filename_{context}"]
= Module Heading

The first sentence of the topic.
----

.Example 1. Concept module
[source]
----
[id="con-guided-decision-tables_{context}"]
= Guided Decision Tables

The guided decision tables feature works similarly to ...
----

.Example 2. Concept module
[source]
----
[id="con_guided-decision-tables_{context}"]
= Guided Decision Tables

The guided decision tables feature works similarly to ...
----


.Example 3. Procedure module
[source]
----
[id="proc-creating-guided-decision-tables_{context}"]
= Creating Guided Decision Tables

You can use guided decision tables to ...
----

.Example 4. Procedure module
[source]
----
[id="proc_creating-guided-decision-tables_{context}"]
= Creating Guided Decision Tables

You can use guided decision tables to ...
----

[NOTE]
.Note on other anchor formats (not recommended)
====
The anchor format defined here is recommended because it is the most stable and versatile of anchor formats, and supports variables that enable topics to be reused and cross-referenced correctly. For details, see xref:reusing-modules[]. Other anchor formats include `+++[[anchor-name]]+++` and `+++[#anchor-name]+++`, but these formats either do not support variables for content reuse or do not support certain character types, such as periods. These limitations cause errors at build time.
====



.Additional resources

* link:https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
