[id='creating-assemblies']
= Creating Assemblies

An assembly is a representation of a user story, so you need to create an assembly for each user story that you defined.

An assembly could represent an article, "chapter" in a book, or even an entire book. However, one of the benefits of modular documentation is that you do not need to worry about how the assembly will ultimately be used -- each assembly represents a user goal, and once you create it, it can be "included" anywhere it is needed (a publication, within another assembly, and so on).

[discrete]
== Procedure

. Create an assembly file for each user story that you identified.
+
--
Be sure to follow the conventions for xref:anchor-and-file-names[naming anchors and files]. For example: `assembly_guided-decision-tables.adoc`
--

. For each top-level assembly file that you created, fill in the content.
+
For more information, see xref:assembly-guidelines[Assembly Guidelines].

. Repeat the previous step for each second-level assembly.
