[id='reusing-modules']
= Reusing Modules in Assemblies

When you create content in modules, you can use the same module multiple times in an assembly without having to replicate information in multiple source files. However, in order to facilitate module reuse, you must embed a document attribute variable in the anchor name for the module and then define that variable in the assembly each time the reused module appears. If the variable is not embedded and assigned, an error appears at build time reporting the duplicated anchor ID.

.Error at Build Time When Anchor Has No Variable
====
[source]
----
ID "$ANCHOR_NAME" is duplicated in the source content
$BUILD_PATH fails to validate
----
====

This error is resolved by adding and defining a document variable.

[discrete]
== Procedure

. In the module file that will be reused, add the `+++{context}+++` suffix with an underscore to the anchor name in the format `[id='anchor-name_+++{context}'+++]`.

+
NOTE: Although you can use any document variable that clearly indicates the variable in question, such as `+++{product}+++` or `+++{chapter}+++`, the `+++{context}+++` variable is recommended. This variable indicates more generally that the same module can be reused in the specified "context" of one section of a document or another, regardless of whether that section is product-specific or not, whether it is a whole chapter or a small assembly, or some other limitation.

+
.Two Modules to Be Reused: Module A and Module B
[source]
----
[id='module-A-being-reused_{context}']
= Module A Heading
----
+
[source]
----
[id='module-B-being-reused_{context}']
= Module B Heading
----

 . In the assembly file or the master book file, define the `+++:context:+++` variable, separated by dashes, immediately above any included modules that are being reused, in the format `+++:context:+++ variable-name`. How you define the variable depends on whether the module is included once in multiple assemblies, or is included multiple times in a single assembly.
+
Module Included Once in Multiple Assemblies:: If the reused modules are included only once in this assembly and in at least one other assembly, define an assembly-level variable such as `+++:context: assembly-name+++`. This  indicates that the reused module is appearing in the context of that assembly.

+
.Assembly 1
[source]
----
include::con_some-module-not-being-reused.adoc

:context: assembly-1-name
include::con_module-A-being-reused.adoc

include::con_some-module-not-being-reused.adoc

:context: assembly-1-name
include::con_module-B-being-reused.adoc
----

+
.Assembly 2
[source]
----
include::con_some-module-not-being-reused.adoc

:context: assembly-2-name
include::con_module-A-being-reused.adoc

include::con_some-module-not-being-reused.adoc

:context: assembly-2-name
include::con_module-B-being-reused.adoc
----

+
Module Included Multiple Times in a Single Assembly:: If a module is included multiple times in the same assembly, define a variable specific to a section or a chapter of that assembly, such as `+++:context: section-name+++`. This  indicates that the reused module is appearing in the context of that section of the assembly.

+
.Assembly
[source]
----
include::con_some-module-not-being-reused.adoc

:context: section-1-name
include::con_module-A-being-reused.adoc

include::con_some-module-not-being-reused.adoc

:context: section-2-name
include::con_module-A-being-reused.adoc
----

+
. Return to the reused module file, and at the top of the file add a comment that identifies which assemblies the module has been added to. This helps to track reused modules in the future.

+
[source]
----
// Module included in the following assemblies:
//
// ...

[id='module-A-being-reused_{context}']
= Module A Heading
----

.Cross-Referencing Reused Modules
[NOTE]
====
To cross-reference a reused module, specify both the anchor name and the `+++{context}+++` variable as defined in the assembly:

[source]
----
xref:anchor-name_context-variable-name[]
----

Example:

[source]
----
For details, see xref:module-A-being-reused_assembly-1-name[].
----
====

[discrete]
== Practical Example 1: Reusing Modules in Multiple Assemblies

You want to reuse the "Creating Assets" procedure module and the "Projects" concept module in two assemblies: an "Asset Definitions" assembly and a "Business Rules" assembly.

The module files contain the following content:

.con_projects.adoc
[source]
----
// Module included in the following assemblies:
//
// assembly_asset-definitions.adoc
// assembly_business-rules.adoc

[id='projects_{context}']
= Projects
----

.proc_creating-assets.adoc
[source]
----
// Module included in the following assemblies:
//
// assembly_asset-definitions.adoc
// assembly_business-rules.adoc

[id='creating-assets_{context}']
= Creating Assets
----

The assembly files contain the following content:

.assembly_asset-definitions.adoc
[source]
----
include::con_organizational-unit.adoc

include::con_repository.adoc

:context: asset-definitions
include::con_projects.adoc

include::con_organizational-unit.adoc

include::proc_creating-packages.adoc

:context: asset-definitions
include::proc_creating-assets.adoc

include::proc_adding-dependencies.adoc
----

.assembly_business-rules.adoc
[source]
----
include::con_business-processes.adoc

:context: business-rules
include::con_projects.adoc

include::ref_project-types.adoc

include::con_packages.adoc

:context: business-rules
include::proc_creating-assets.adoc
----

For all cross-references to the reused modules, specify which context (assembly) you want to link to. For example, you can link to the "Creating Assets" procedure module as it appears either in the "Asset Definitions" assembly or in the "Business Rules" assembly. Create cross-references in the `+++xref:anchor-name_context-variable-name[]+++` format:

[source]
----
For details, see xref:creating-assets_asset-definitions[].
----

or

[source]
----
For details, see xref:creating-assets_business-rules[].
----

[discrete]
== Practical Example 2: Reusing a Module in a Single Assembly

You want to reuse the "Projects" concept module twice in the "Business Rules" assembly.

The module file contains the following content:

.con_projects.adoc
[source]
----
[id='projects_{context}']
= Projects
----

The assembly file contains the following content:

.assembly_business-rules.adoc
[source]
----
:context: intro
include::con_projects.adoc

include::con_organizational-unit.adoc

include::ref_asset-types.adoc

:context: asset-types
include::con_projects.adoc

include::con_dependencies.adoc
----

For all cross-references to the reused module, specify which context (section) you want to link to. For example, you can link to the "Projects" module as it appears either in the "Introduction" or in the "Asset Types" section. You create cross-references in the format `+++xref:anchor-name_context-variable-name[]+++`:

[source]
----
For details, see xref:projects_introduction[].
----

or

[source]
----
For details, see xref:projects_asset-types[].
----

[discrete]
== Additional Resources

* The link:http://asciidoctor.org/docs/user-manual/#include-multiple[Asciidoctor User Manual].
