[id='a-simple-example-of-a-modular-guide']
= A Simple Example of a Modular Guide

Download and unzip link:https://github.com/redhat-documentation/modular-docs/blob/master/modular-docs-manual/files/simple-mod-guide-repo.zip[an example modular guide]. The `simple-mod-guide-repo` directory included in the ZIP archive contains a very simple example of a modular guide with assemblies and modules. This section explains the contents of the directory.

NOTE: To build the example guide, change into the `simple-mod-guide-repo` directory, issue the *asciidoctor master.adoc* command, and open the resulting `master.html` file in your browser.

`master.adoc`:: File that defines the whole book. It pulls in the `attribute.adoc` file with AsciiDoc attributes, sets the title of the book, and pulls in the assemblies that comprise the book.

`docs/`, `docs/modules/`:: Directories that include the actual documentation: assemblies and modules.

`docs/assembly-1.adoc`, `docs/assembly-2`:: Simple assembly files with include statements that pull in modules.

`docs/modules/module-a.adoc`, `docs/modules/module-b.adoc`, ...:: Simple module files. Some of them demonstrate how to reuse a module in multiple assemblies.
+
In `module-b.adoc`, note the use of the AsciiDoc conditional (`ifeval`) to reuse the same module with some differences.

Feel free to experiment with the example guide: create new assemblies and modules, reuse modules, introduce new AsciiDoc conditionals.
