[id='modular-docs-terms-definitions']
= Modular Documentation Terms and Definitions

Assembly:: A collection of several modules combined into a larger piece of text, preceded by an introduction that explains the purpose of the assembly.
+
The docs realization of a _user story_.

Module:: A building block of information with a well-organized structure.
+
Because modules are written as context-free elements independent of other modules, they are re-usable. One module can be part of multiple assemblies.
+
Concept Module::: Explains a concept; for example, not action-based.
Procedure Module::: Describes steps to perform an action.
Reference Module::: Presents detailed reference material, for example, command syntax.

User Story:: A short description of something the user does to achieve a goal.
+
Example: As an administrator, I want to set up authentication to a critical system in my infrastructure, such as a gateway VPN, or accounting system to only allow users authenticated via strong authentication methods, for example two-factor authentication.
+
As opposed to a _use case_, which is a description of interactions between the system and the user or other systems.
+
.Contrasting User Stories and Use Cases
[grid="rows"]
[options="header",width=100%,cols="10%s,45%a,45%a"]
|===
| | User Story | Use Cases
| Definitions: | A short description of something the user does to achieve a goal. | A description of interactions between the system and the user, components of the system, or the system and other systems.
| Views the situation from: | The perspective of a user. | The perspective of a product and its features.
| Focuses on: | The outcome as perceived by the user. | What the product does and how it does it, which includes product requirements, specification, scope.
| Example:
| As an office worker, I want to be able to easily switch between standing and sitting, so that I prevent back pain and other health issues associated with prolonged periods of sitting at a computer.

NOTE: This user story follows a common template for user stories in the form of "As a <type_of_user>, I want <some_goal> so that <some_reason>."

| Ergonomic work space solution - a standing desk that allows switching between standing and sitting. The standing desk:

* Is motorized, with a button a person can press to adjust the height; the height must span up to 150 cm to be usable also by people 200 cm tall.
* Is made from easy-to-clean and durable material to withstand standard office conditions, such as spilled tea or scratches: table top - polyester, legs - steel.
* Has large enough work surface to comfortably fit 2 monitors, one laptop docking station, small personal items.
* Can hold the weight of 100 kg, such as standard office equipment and a person sitting on the desk.
* Meets safety requirements per EU standards for office equipment.
* Has attractive design to fit in modern office spaces.

NOTE: A use case like this can also include other ergonomic solutions, such as an adjustable sit-stand wall mount for monitors and compare their parameters, such as ease of installation, price, and ease of use.

|===
+
[IMPORTANT]
====
To fulfill their purpose, user stories must be defined based on customer needs. Therefore, they must be produced by customer-facing associates, such as product management or field teams, not by writers. Writers can only help polish the user stories if required.

If your team does not have user stories, do not write them yourselves. Instead, ask the stakeholders for your product to provide them to you.
====

User story-based docs:: Docs developed to support a user story. For our purposes, user-story-based docs are the same as use-case-based docs.

Modular docs:: Documents structured into modules and assemblies.

NOTE: We do not use the terms _topic_ or _topic-based documentation_ because they are too ambiguous. A _topic_ can mean a piece of documentation, a user story, or a short chunk of content. Therefore, topic-based can mean a number of things.
