[id="module_anchor-and-file-names-concept"]
= File Names and Anchors

To optimize modular documentation, follow these guidelines for naming files and creating anchors:

.File names
Assembly and module file names should accurately and closely reflect the title of the assembly or module. File names should have the format `prefix-filename.adoc` or `prefix_filename.adoc` where `prefix` is one of the following module prefixes:

* `con`: Concept module prefix
* `proc`: Procedure module prefix
* `ref`: Reference module prefix
* `assembly`: Assembly module prefix

.Examples
* `con-guided-decision-tables.adoc`  (Concept module)
* `proc-creating-guided-decision-tables.adoc`  (Procedure module for creating)
* `proc-editing-guided-decision-tables.adoc`  (Procedure module for editing)
* `ref-guided-decision-table-examples.adoc`  (Reference module with examples)
* `ref-guided-decision-table-columns.adoc`  (Reference module with column types)
* `assembly-designing-guided-decision-tables.adoc`  (Assembly of guided decision table modules)


[NOTE]
====
Do not include special characters in file names. Ensure that all members of your team use the same file naming conventions.
====

These file naming guidelines are optional but highly recommended. However, if your team does not include the module prefixes in file names followed by either a hyphen (-) or an underscore (_), you must include one of the following variables in each concept, procedure, and reference module:

NOTE: This is a Pantheon 2 requirement.

[source]
----
:system-module-type: CONCEPT
:system-module-type: PROCEDURE
:system-module-type: REFERENCE
----



.Anchors
At the top of every module, provide an anchor in the format `+++[id="filename_{context}"]+++` where `filename` is the exact name of the file, without the file extension (`.adoc`). Module anchors are necessary so that the module can be identified by Asciidoctor when reused or cross-referenced. The `{context}` variable is intentionally not defined in the module anchor ID. You define a context value in each assembly, in the format `:context: my-context-value`. This enables the context variable in each module to be populated according to the relevant assembly.
--
[source]
----
[id="filename_{context}"]
= Module Heading

The first sentence of the topic.
----

.Example 1. Concept Module
[source]
----
[id="con-guided-decision-tables_{context}"]

= Guided Decision Tables

The guided decision tables feature works similarly to ...
----

.Example 2. Procedure Module
[source]
----
[id="pro-creating-guided-decision-tables_{context}"]
= Creating Guided Decision Tables

You can use guided decision tables to ...
----

[NOTE]
.Note on Other Anchor Formats (Not Recommended)
====
The format defined here is recommended because it is the most stable and versatile of anchor formats, and supports variables that enable topics to be reused and cross-referenced properly. For details, see xref:reusing-modules[]. Other anchor formats include `+++[[anchor-name]]+++` and `+++[#anchor-name]+++`, but these formats either do not support variables for content reuse or do not support certain character types, such as periods. These limitations cause errors at build time.
====

--

.Additional Resources

* link:https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
