[id='modular-docs-procedure-examples']
= Procedure Module Examples

.Procedure Module: Installing Third-Party Certificates for HTTP or LDAP
====
*PROCEDURE TITLE*

Installing Third-Party Certificates for HTTP or LDAP

*PURPOSE*

Installing a new SSL server certificate for the Apache Web Server, the Directory Server, or both replaces the current SSL certificate with a new one.

*PREREQUISITES*

* To install the certificate, you need your private SSL key (`ssl.key` in the procedure below) and your SSL certificate (`ssl.crt` in the procedure below).
+
For a list of accepted formats of the key and certificate, see the ipa-server-certinstall(1) man page.
* The `ssl.crt` certificate must be signed by a certificate authority (CA) known by the service you are loading the certificate into.
+
If this is not the case, install the CA certificate of the CA that signed `ssl.crt` into IdM, as described in Section 34.3, “Installing a CA Certificate Manually”.

*STEPS*

. Use the **ipa-server-certinstall** utility to install the certificate.
+
For example, to install the SSL certificate into the Apache Web Server (**--http**) as well as the Directory Server (**--dirsrv**):
+
....
# ipa-server-certinstall --http --dirsrv ssl.key ssl.crt
....

. Restart the server into which you installed the certificate.
+
To restart the Apache Web Server:
+
....
# systemctl restart httpd.service
....
+
To restart the Directory Server:
+
....
# systemctl restart dirsrv@REALM.service
....

. To verify that the certificate has been correctly installed, make sure it is present in the certificate database.
+
To display the Apache certificate database:
+
....
# certutil -L -d /etc/httpd/alias
....
+
To display the Directory Server certificate database:
+
....
# certutil -L -d /etc/dirsrv/slapd-REALM/
....

*RELATED INFORMATION*

N/A
====

.Procedure Module: Raising the Domain Level
====
*PROCEDURE TITLE*

Raising the Domain Level

*PURPOSE*

IMPORTANT: This is a non-reversible operation. If you raise the domain level from 0 to 1, you cannot downgrade from 1 to 0 again.

*PREREQUISITES*

N/A

*STEPS*

. Log in as the administrator:
+
....
$ kinit admin
....
. Run the **ipa domainlevel-set** command and provide the required level:
+
....
$ ipa domainlevel-set 1
-----------------------
Current domain level: 1
-----------------------
....

*RELATED INFORMATION*

N/A
====


.Procedure Module (Troubleshooting): External Certificate Authority Installation Fails
====
*PROCEDURE TITLE*

External Certificate Authority Installation Fails

*PURPOSE*

The **ipa-server-install --external-ca** command fails with the following error:

....
ipa         : CRITICAL failed to configure ca instance Command '/usr/sbin/pkispawn -s CA -f /tmp/configuration_file' returned non-zero exit status 1
Configuration of CA failed
....

The **env\|grep proxy** command displays variables such as the following:

....
http_proxy=http://example.com:8080
ftp_proxy=http://example.com:8080
https_proxy=http://example.com:8080
....

**What this means:**

The ***_proxy** environmental variables are preventing the server from being installed.

*PREREQUISITES*

N/A

*STEPS*

**To fix the problem:**

. Use the following shell script to unset the ***_proxy** environmental variables:
+
....
# for i in ftp http https; do unset ${i}_proxy; done
....

. Run the **pkidestroy** utility to remove the unsuccessful CA subsystem installation:
+
....
# pkidestroy -s CA -i pki-tomcat; rm -rf /var/log/pki/pki-tomcat  /etc/sysconfig/pki-tomcat  /etc/sysconfig/pki/tomcat/pki-tomcat  /var/lib/pki/pki-tomcat  /etc/pki/pki-tomcat /root/ipa.csr
....

. Remove the failed IdM server installation:
+
....
# ipa-server-install --uninstall
....

. Retry running the **ipa-server-install --external-ca** command.

*RELATED INFORMATION*

N/A
====

.Procedure Module (Troubleshooting): All Monitors Failed to Start Because of a Corrupted Store
====
*PROCEDURE TITLE*

All Monitors Failed to Start Because of a Corrupted Store

*PURPOSE*

All Ceph Monitors terminated unexpectedly or failed to start. In addition, one or both of the following error messages are logged to the monitor log:

....
Corruption: error in middle of record
Corruption: 1 missing files; e.g.: /var/lib/ceph/mon/mon.0/store.db/1234567.ldb
....

**What this means:**

Ceph Monitors store the cluster map in a key-value store such as LevelDB. If the store is corrupted on a Monitor, the Monitor terminates unexpectedly and fails to start again.

Production clusters must use at least three Monitors, so that if one Monitor fails, it can be replaced with a new one. However, under certain circumstances, all Monitors can have corrupted stores. For example, when the Monitor nodes have improperly configured disk or file system settings, the underlying file system can be corrupted after a power outage.

*PREREQUISITES*

N/A

*STEPS*

**To fix the problem:**

If the store is corrupted on all Monitors, you can recover it with the information stored on the Object Storage Device (OSD) nodes by using utilities called **ceph-monstore-tool** and **ceph-objectstore-tool**.

Before you start:

* Ensure that you have the **rsync** utility installed.

Run the following commands from the Monitor node with the corrupted store:

. (...)
. (...)
. (...)

*RELATED INFORMATION*

**Additional Resources**

* See Installing Ceph Ansible for details.
====
