
[id="con-concept-explanation_{context}"]

= Concept explanation

[role="_abstract"]
A short introductory paragraph that provides an overview of the module is required.
It provides an overview of the module. The `[role="_abstract"]` tag defines the first paragraph of the module for search metadata.

The contents of a concept module give the user descriptions and explanations needed to understand and use a product.

* Look at nouns and noun phrases in related procedure modules and assemblies to find the concepts to explain to users.
* Explain only things that are visible to users. Even if a concept is interesting, it probably does not require explanation if it is not visible to users.
* Do not include any instructions to perform an action, such as executing a command. Action items belong in procedure modules.

[role="_additional-resources"]
.Additional resources
// An optional bulleted list of links to other material closely related to the contents of the concept module.

* link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide]
* link:https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
