
[id="proc-doing-one-procedure_{context}"]

= Doing one procedure

[role="system:abstract"]
A short introductory paragraph that provides an overview of the module is required. Procedure modules should include both what users will do and why users want to do it.
The `[role="system:abstract"]` tag defines the first paragraph of the module for search metadata.


.Prerequisites (optional)

* A bulleted list of conditions that must be satisfied before the user starts following this assembly.
* You can also link to other modules or assemblies the user must follow before starting this assembly.
* Delete the section title and bullets if the assembly has no prerequisites.

.Procedure

. Start each step with an active verb.

. Include one command or action per step.

. Use an unnumbered bullet (*) if the procedure includes only one step.

.Additional resources (optional)

* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
