[id="ref-reference_{context}"]

= Reference material

[role="system:abstract"]
A short introductory paragraph that provides an overview of the module is required.
The `[role="system:abstract"]` tag defines the first paragraph of the module for search metadata.

A reference module provide data that users might want to look up. A reference module does not contain procedures or detailed concept information. It has a very strict structure, often in the form of a list or a table. A well-organized reference module enables users to scan it quickly to find the details they want.
AsciiDoc markup to consider for reference data:

.Unordered list
* For more details on writing reference modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles.


.Labeled list
Term 1:: Definition
Term 2:: Definition

.Table
[options="header"]
|====
|Column 1|Column 2|Column 3
|Row 1, column 1|Row 1, column 2|Row 1, column 3
|Row 2, column 1|Row 2, column 2|Row 2, column 3
|====
