[id='con-dmn-support_{context}']
= DMN support in {PRODUCT}

{PRODUCT} provides design and runtime support for DMN 1.2 models at conformance level 3, and runtime-only support for DMN 1.1 and 1.3 models at conformance level 3. You can design your DMN models with the {PRODUCT} DMN modeler in VSCode or import existing DMN models into your {PRODUCT} projects for deployment and execution. Any DMN 1.1 models that you import into your {PRODUCT} project, open in the DMN modeler, and save are converted to DMN 1.2 models. DMN 1.3 models are not supported in the {PRODUCT} DMN modeler.

In addition to all DMN conformance level 3 requirements, {PRODUCT} also includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. From a platform perspective, DMN models are like any other business asset in {PRODUCT}, such as DRL files or spreadsheet decision tables, that you can include in your {PRODUCT} project and execute to start your DMN decision services.
