== Legal Notice

Copyright (C) {YEAR} Red Hat, Inc.

This document is licensed by Red Hat under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-ShareAlike 3.0 Unported License].
If you distribute this document, or a modified version of it, you must provide attribution to Red Hat, Inc.
and provide a link to the original.
If the document is modified, all Red Hat trademarks must be removed.

Red Hat, as the licensor of this document, waives the right to enforce, and agrees not to assert, Section 4d of CC-BY-SA to the fullest extent permitted by applicable law.

Red Hat, Red Hat Enterprise Linux, the Shadowman logo, JBoss, MetaMatrix, Fedora, the Infinity Logo, and RHCE are trademarks of Red Hat, Inc., registered in the United States and other countries.

Linux(R) is the registered trademark of Linus Torvalds in the United States and other countries.

Java(R) is a registered trademark of Oracle and/or its affiliates.

XFS(R) is a trademark of Silicon Graphics International Corp.
or its subsidiaries in the United States and/or other countries.

MySQL(R) is a registered trademark of MySQL AB in the United States, the European Union and other countries.

Node.js(R) is an official trademark of Joyent.
Red Hat Software Collections is not formally related to or endorsed by the official Joyent Node.js open source or commercial project.

The OpenStack(R) Word Mark and OpenStack Logo are either registered trademarks/service marks or trademarks/service marks of the OpenStack Foundation, in the United States and other countries and are used with the OpenStack Foundation's permission.
We are not affiliated with, endorsed or sponsored by the OpenStack Foundation, or the OpenStack community.

All other trademarks are the property of their respective owners.
