[id='proc-kogito-running-app_{context}']
= Running a {PRODUCT} service

After you design the business decisions and processes for your {PRODUCT} service, you can run your Quarkus or Spring Boot application in one of the following modes:

* *Development mode*: For local testing. On Quarkus, development mode also offers live reload of your processes and decisions in your running applications for advanced debugging.
* *JVM mode*: For compatibility with a Java virtual machine (JVM).
ifdef::KOGITO-COMM[]
* *Native mode*: (Quarkus only, requires GraalVM) For direct binary execution as native code.
endif::[]

.Procedure
In a command terminal, navigate to the project that contains your {PRODUCT} service and enter one of the following commands, depending on your preferred run mode and application environment:

* For development mode:
+
--
.On Quarkus
[source]
----
mvn clean compile quarkus:dev
----

.On Sprint Boot
[source]
----
mvn clean compile spring-boot:run
----
--
* For JVM mode:
+
--
.On Quarkus and Spring Boot
[source]
----
mvn clean package
java -jar target/sample-kogito-1.0-SNAPSHOT-runner.jar
----
--
ifdef::KOGITO-COMM[]
* For native mode (requires GraalVM):
+
--
.On Quarkus only
[source]
----
mvn clean package -Dnative
./target/sample-kogito-1.0-SNAPSHOT-runner
----
--
endif::[]
