// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


// Include an 'ID' that corresponds to the title of the assembly
// The ID will be used as an anchor for linking to the title
// Do not change the ID to make sure existing links keep working
[#concept-template-and-guidelines_{context}]
= Concept Template and Guidelines

_In the title, include nouns that are used in the body text -- this helps readers and search engines find information quickly._

// Ideally, base the name of the file on the title to avoid confusion
// Use a consistent system for filenames and IDs, e.g.:
//  * Only substitute spaces with underscores
//  * Don't use any CAPS

A concept module describes and explains things such as a product, subsystem, or feature -- what a customer needs to understand to do a task. A concept module may also explain how things relate and interact with other things. The use of graphics and diagrams can speed up understanding of a concept.

* Look at nouns and noun phrases in related task modules and user story assemblies to find the concepts to explain to users.

* A concept module in product documentation should explain only things that are visible to users.

* If a product concept is interesting, but not visible to users, the concept probably does not require explanation in a concept module.

* A concept module should NOT include numbered steps or other wording that instructs a user to execute a command or perform an action. Instead, put that information in a separate task module or user story assembly.
